name: Build GP4K Greenplum Ubuntu Image
on:
  push:
    branches:
      - main
jobs:
  build-greenplum-image:
    name: Greenplum GP4K Image Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Create tag
        id: docker_tag
        run: |
          commit_tag=${GITHUB_REF#refs/*/}
          echo "tag=${commit_tag}-${{ github.run_number }}" >> $GITHUB_OUTPUT
      - name: Verify tag
        run: echo ${{ steps.docker_tag.outputs.tag }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          pull: true
          no-cache: true
          file: greenplum-instance/Dockerfile
          build-args: |
            PLAID_BUILD_TAG=${{ steps.docker_tag.outputs.tag }}
          tags: jike21/greenplum-gp4k:v1-20231104
